groups:
  - name: node_exporter_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage ({{ $value }}%)"
          description: "Instance {{ $labels.instance }} has CPU usage exceeding 85%."

      - alert: LowDiskSpace
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100 < 10
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space ({{ $value }}%)"
          description: "Instance {{ $labels.instance }} on partition {{ $labels.mountpoint }} has less than 10% free space."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage ({{ $value }}%)"
          description: "Instance {{ $labels.instance }} has RAM usage exceeding 90%."