global:
  slack_api_url: 'https://hooks.slack.com/services/xxxxxxxxxxx/yyyyyyyyyy/xxxxxxxxxxxxxx'

route:
  group_by: ['alertname']
  receiver: 'multi-channel'
  
receivers:
  - name: 'multi-channel'
    slack_configs:
      - channel: '#alerts'
        send_resolved: true
        username: 'Prometheus'
        icon_emoji: ':warning:'
