# rules.yml
groups:
- name: example_alerts
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on{{ $labels.instance }}"
      description: "CPU load on {{ $labels.instance }} exceeded 80%."
