# http-rules.yml
groups:
- name: Http_alerts
  rules:
  - alert: WebsiteDown
    expr: probe_success{job="blackbox"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Web-Sait {{ $labels.instance }} is broked "
      description: "Check for {{ $labels.instance }} been no results over time 1 minute."